# version: '3'
# services:
#   zookeeper:
#     image: confluentinc/cp-zookeeper:latest
#     ports:
#       - "2181:2181"
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181  # Add this line
#     networks:
#       - project-net

#   kafka:
#     image: confluentinc/cp-kafka:latest
#     ports:
#       - "9092:9092"
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
#       KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
#       KAFKA_LISTENERS: INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
#       KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#     depends_on:
#       - zookeeper
#     networks:
#       - project-net

#   spark:
#     image: bitnami/spark:latest
#     volumes:
#       - /c/Users/Administrateur/Desktop/twitter_app_project:/twitter/project/
# networks:
#   project-net:
#     driver: bridge
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - project-net

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - project-net

  spark:
    image: bitnami/spark:latest
    volumes:
      - /c/Users/Administrateur/Desktop/twitter_app_project:/twitter/project/
    environment:
      MONGO_HOST: host.docker.internal
      SPARK_MASTER: local[*]
      SPARK_DRIVER_HOST: host.docker.internal
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      - kafka
    networks:
      - project-net

networks:
  project-net:
    driver: bridge
